import bodyBgc from '../../public/bodyBgc.avif'
import './globals.css'

export const metadata = {
  title: 'Aggstool'
  // description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="" style={{ backgroundImage: `url('${bodyBgc.src}')` }}>
        {children}
      </body>
    </html>
  )
}
